// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetValue() {
  return window['go']['main']['App']['GetValue']();
}

export function SetValue(arg1) {
  return window['go']['main']['App']['SetValue'](arg1);
}
